CREATE TABLE "detail" (
"id"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"title"  TEXT,
"aid"  TEXT,
"price"  TEXT,
"unitprice"  TEXT,
"xiaoqu"  TEXT,
"jushi"  TEXT,
"mianji"  TEXT,
"chaoxiang"  TEXT,
"louceng"  TEXT,
"niandai"  TEXT,
"nianxian"  TEXT,
"chanquan"  TEXT,
"dianti"  TEXT,
"quanshu"  TEXT,
"guapaidate"  TEXT,
"shangcidate"  TEXT,
"weiyi"  TEXT,
"jingshoufu"  INTEGER,
"shui"  INTEGER,
"qita"  INTEGER,
"zongshoufu"  INTEGER,
"url"  TEXT,
"status"  INTEGER DEFAULT 0,
"rv1"  TEXT,
"rv2"  TEXT,
"rv3"  TEXT,
"ctime"  TEXT,
"upd"  TEXT,
"remark"  TEXT,
"quyu"  text,
"qu"  TEXT
)